basePath: /
definitions:
  models.Item:
    properties:
      price:
        description: |-
          The price of the item.
          Required: true
          pattern: ^\d+\.\d{2}$
        type: string
      shortDescription:
        description: |-
          The short description of the item.
          Required: true
          pattern: ^[\s\w-]+$
        type: string
    required:
    - price
    - shortDescription
    type: object
  models.PointsResponse:
    properties:
      points:
        description: The total points earned from the receipt.
        type: integer
    type: object
  models.ProcessReceiptResponse:
    properties:
      id:
        description: The unique identifier for the receipt.
        type: string
    type: object
  models.ReceiptRequest:
    properties:
      items:
        description: |-
          The list of items in the receipt.
          Required: true
        items:
          $ref: '#/definitions/models.Item'
        minItems: 1
        type: array
      purchaseDate:
        description: |-
          The date of purchase.
          Required: true
        type: string
      purchaseTime:
        description: |-
          The time of purchase.
          Required: true
        type: string
      retailer:
        description: |-
          The name of the retailer.
          Required: true
          pattern: ^[\w\s\-&]+$
        type: string
      total:
        description: |-
          The total amount of the receipt.
          Required: true
          pattern: ^\d+\.\d{2}$
        type: string
    required:
    - items
    - purchaseDate
    - purchaseTime
    - retailer
    - total
    type: object
host: localhost:5555
info:
  contact: {}
  title: Fetch Receipt Processor
  version: "0.1"
paths:
  /receipts/{id}/points:
    get:
      description: Returns the points awarded for the receipt.
      parameters:
      - description: Receipt ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PointsResponse'
        "404":
          description: No receipt found for that ID.
          schema:
            type: string
      summary: Returns the points awarded for the receipt.
      tags:
      - receipts
  /receipts/process:
    post:
      description: Submits a receipt for processing.
      parameters:
      - description: Receipt
        in: body
        name: receipt
        required: true
        schema:
          $ref: '#/definitions/models.ReceiptRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ProcessReceiptResponse'
        "400":
          description: The receipt is invalid.
          schema:
            type: string
      summary: Submits a receipt for processing.
      tags:
      - receipts
swagger: "2.0"
